### PR TITLE
Pawn promotion

### PR DESCRIPTION
**Pull request by kristinh12**
Still a WIP.

We completed the back-end for pawn promotion, and added a modal for selecting the piece.  We are still working on getting the modal to display only when a pawn is being promoted.

### CODE REVIEW

**Comment by RaykPlatzek** [comment]
@roderickjoseph  @kristinh12 while working on the modal for the promotion have a look at the web socket implementation and keep in mind that the page will not be reloading after each move like before (which means the instance variables in the view might not be updated).

**Comment by RaykPlatzek** [comment]
@kristinh12 @roderickjoseph I tried a couple of thinks and found this solution:
 you can hide your button and give it and ID and each time your want to show your modal you just use $("#promo_button").click();. I pushed up a test branch where the modal shows up when a pawn reaches row 7 or 0 ( name of branch: try_to_get_modal_to_view) it includes the new master changes and the castling changes. Should be a clean branch to start with

**Comment by RaykPlatzek** [comment]
@roderickjoseph @kristinh12 

No piece can move because the promotion check is a private function which is called outside of the model from the piece controller
Also, we would need to check if the piece moved is a pawn otherwise it will through an error for every other piece moved

So if you adjust the code to:
  def pawn_promotion?(destination_y)
    return true if destination_y.zero? || destination_y == 7
    false
  end

  def promote!
    # byebug
    update(type: 'Queen')
  end

  private

and then in the controller:
if @piece.type == 'Pawn' && @piece.pawn_promotion?(destination_y)

This will work.

**Comment by RaykPlatzek** [comment]
Would suggest you delete comments that you don't need anymore (otherwise the code becomes hard to read). For the next steps I would do the following:

0. in the view check if promotion is true and then show the modal
1. Try to get the modal to show up with a buttons / images to click on ("Queen, Knight, Bishop, Rock") 
2. Save the choice the user made in a variable and then add it to our existing ajax request
(e.g. give each button an id and then run:
let promotion = ""; 
$("#Queen").click( function()
           {
             promotion = "Queen";
           }
3. I would then use the existing ajax request that we have as it is already sending through the piece id and just ad the promotion variable to it

4. Front-End: check the promotion choice and change the piece image to be the image of choice but keep the id of the piece the same

5. Back-End: check in the controller if  promotion variable from view .present? (this saves us to check 
 for promotion a second time) 

6. move the piece to destination and after that update current piece type with new type of choice but keep all other attributes the same

**Comment by kristinh12** [comment]
Tests need to be rewritten in pieces_controller_spec instead of pawn_spec.

Bug: After pawn promotion the wrong turn is displayed.

**Comment by RaykPlatzek** [comment]
as discussed with Roderick next steps would be:
- deleting the window reloading after each promotion
- changing the piece image as per choice using piece.find("img").attr('src, ****** url of image for promotion choice here***), preferably in the   $('#queenButton').on('click', function() of each piece
- in piece_moved_channel.bind('piece_moved', function(data)  checking for a pawn promotion via if statement and only deleting the destination piece otherwise continue with the routine for a regular move / en_passant_move or castling move
- the rest should already be handled correctly in the back-end

**Comment by wphoong** [comment]
Great job! Pawn promotion is working on both sides for me.

1. After the pawn promotion is done, another modal pops up.

**Pull request merged**
