### PR TITLE
WIP - Created castle? method.  Yet to implement the move into the game.

### PR DESCRIPTION
**Pull request by roderickjoseph**

### CODE REVIEW

**Comment by roderickjoseph** [comment]
Mind taking a look at this @mscoutermarsh ?  All of our tests are passing, but it is not working in a game.  FYI - Kristin did point out a bug with the Pawn capture allowing pawns to capture pieces from any distance.

**Comment by mscoutermarsh** [comment]
@roderickjoseph can you point me to what part of the code isn't working?

**Comment by roderickjoseph** [comment]
Mind taking a look at this one @mscoutermarsh .  Castling appears to work.  Some of the checkmate and stalemate tests are not passing still.

**Comment by RaykPlatzek** [comment]
I had a look and the following changes will fix your problems:

First we need to check if castling is true in the valid_move? function otherwise it will allow these moves to be valid even if there is no castling situation.
Secondly, we need to check if the king is on column 4 before castling otherwise it will apply the castling logic when it tries to move to column 6 or 2 from a column other than 4 as well. 

  def move_to!(destination_x, destination_y)
    if castle?(destination_x, destination_y)
      castle!(7, 0) if destination_x == 6 && destination_y.zero?
      castle!(0, 0) if destination_x == 2 && destination_y.zero?
      castle!(7, 7) if destination_x == 6 && destination_y == 7
      castle!(0, 7) if destination_x == 2 && destination_y == 7
    else
      super
    end
  end


   return true if (destination_x == 2 && destination_y.zero? && color == 'white' && moved? == false ||
                   destination_x == 6 && destination_y.zero? && color == 'white' && moved? == false ||
                   destination_x == 2 && destination_y == 7 && color == 'black' && moved? == false ||
                   destination_x == 6 && destination_y == 7 && color == 'black' && moved? == false) &&
                   castle?(destination_x, destination_y)


  def castle?(rook_column_coordinate, rook_row_coordinate)
   return false unless column_coordinate == 4   
 rook = game.pieces.find_by(column_coordinate: rook_column_coordinate, row_coordinate: 
rook_row_coordinate, type: 'Rook')
    return false if moved?
    return false if rook.nil? || rook.moved?
    return false if obstructed?(rook_column_coordinate, rook_row_coordinate)
    return false if game.check?
    
.....

I tested the code locally and all test will pass after these changes.
Just some code refactoring and rubocop offenses left.

**Comment by roderickjoseph** [comment]
Hi @mscoutermarsh .  Is this one OK to merge?

**Pull request merged**
