### PR TITLE
En passant

### PR DESCRIPTION
**Pull request by RaykPlatzek**
debugging of front-end:
piece will be now removed after en passant move

debugging of back-end:
flag raised in game will be reset after calling check?
after en passant flag will now be reset to nil (reload needed to be added back to valid_move_possible method in game model )

### CODE REVIEW

**Comment by RaykPlatzek** [comment]
ready for review

**Comment by wphoong** [comment]
When I capture black pawn using en passant with a white pawn, it works as expected. However, when I capture a white pawn using en passant using a black pawn, some bugs appear. 

From the picture position, if the black pawn uses en passant to capture the white pawn next to it(white just made a two step move), the white pawn gets captured, however after continuing the game for a few moves, the captured white pawn reappears.

screen shot 2017-07-10 at 7 13 50 pm

When I move the white pawn at (row: 1, column: 4), two steps forward and try the en_passant using the same black pawn(same position as in picture), the move doesn't work.

**Comment by RaykPlatzek** [comment]
@wphoong 
I tried your position but could not reproduce the bug that you mentioned (white pawn reappears).
What moves did you make to have the white pawn reappear ?

**Comment by RaykPlatzek** [comment]
@wphoong  
also the second bug could not reproduced by me.
When I move the pawn at (row: 1, column: 4) two steps forward and then immediately after that try to capture it the en passant works as expected (please see below image).
Have you maybe done a move in between ? In this case you can't move en_passant anymore according the the rules of chess. 
image

**Comment by wphoong** [comment]
https://drive.google.com/open?id=0B9MTEGsphLPhSEJ3Wkx2YlUwTFU

Let me know, if you aren't able to view/download the video

**Comment by RaykPlatzek** [comment]
Ok think I got it working. There were a couple of bugs.
1. The method to check if you move into check was not resetting the en_passant piece if it was captured
2. When checking for a possible move (for stale or checkmate) the en_passant piece needs to be put back as well
3. In the pawn spec files there was a test which used ".and_not change" which does not exist in the rspec syntax. There is a similar syntax (.to not_change) but this is not applicable in our case so I had to change it.

@wphoong feel free to have another review and let me know if there are any issues

**Pull request merged**
